name: Daily Birthday Wisher

on:
  schedule:
    - cron: "30 3 * * *"
  workflow_dispatch:

jobs:
  birthday-wisher:
    runs-on: ubuntu-latest

    steps:
      - name: Get my code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install -r requirements.txt
        working-directory: Day-032-Automated-Birthday-Wisher

      - name: Run Birthday Wisher
        env:
          MY_EMAIL: ${{ secrets.MY_EMAIL }}
          MY_PASSWORD: ${{ secrets.MY_PASSWORD }}
        run: python main.py
        working-directory: Day-032-Automated-Birthday-Wisher
